# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-13 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40, verbose_name='邮箱')),
                ('uname', models.CharField(max_length=40, verbose_name='用户名')),
                ('upassword', models.CharField(max_length=40, verbose_name='密码')),
                ('isactive', models.BooleanField(default=True, verbose_name='是否激活')),
                ('phone', models.CharField(max_length=40, verbose_name='电话')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
    ]
