# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-13 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinfo', '0001_initial'),
        ('memberapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccount', models.IntegerField(verbose_name='数量')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberapp.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(max_length=50, verbose_name='订单号')),
                ('ads', models.CharField(max_length=200, verbose_name='收货人')),
                ('acot', models.IntegerField(verbose_name='总数')),
                ('cals', models.TextField(null=True, verbose_name='商品详细信息')),
                ('orderStatus', models.IntegerField(choices=[(1, '未支付'), (2, '支付中'), (3, '已支付'), (4, '订单取消')], default=1, verbose_name='订单状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo')),
            ],
        ),
    ]
